### ISSUE TITLE
RECLIST v1 for Windows shows as mojibake in oremo

### ISSUE THREAD

**Issue by eijhei** [InochiPM/Vocaloid-Reclist#1]
If you load the comment file from the reclist, it is encoded in UTF-8 which oremo don't like so it shows up as random characters. you need to re-save it as ANSI for it to work normally
[Articulation_list-comment.txt](https://github.com/user-attachments/files/15837657/Articulation_list-comment.txt)
[Stationary_list-comment.txt](https://github.com/user-attachments/files/15837658/Stationary_list-comment.txt)
^ hopefully fixes the sta and art

**Comment by InochiPM** [comment]
Fixed, though the EVEC Blends probably wont work correctly. Ill have to fix them in the future.
